#!/system/bin/sh
WAIT=0.75

/blackbox/draw.sh 0
sleep $WAIT
/blackbox/draw.sh 1
sleep $WAIT
/blackbox/draw.sh 2
sleep $WAIT
/blackbox/draw.sh 3
sleep $WAIT
/blackbox/draw.sh 4
sleep $WAIT
/blackbox/draw.sh 5
sleep $WAIT
/blackbox/draw.sh 6
sleep $WAIT
/blackbox/draw.sh 7
sleep $WAIT
/blackbox/draw.sh 8
sleep $WAIT
/blackbox/draw.sh 9
sleep $WAIT
/blackbox/draw.sh 10
sleep $WAIT
/blackbox/draw.sh 11
sleep $WAIT
/blackbox/draw.sh 12
sleep $WAIT
/blackbox/draw.sh 13
sleep $WAIT
/blackbox/draw.sh 14
sleep $WAIT
/blackbox/draw.sh 15
sleep $WAIT
/blackbox/draw.sh 16
sleep $WAIT
/blackbox/draw.sh 17
sleep $WAIT
/blackbox/draw.sh 18
sleep $WAIT
/blackbox/draw.sh 19
sleep $WAIT
/blackbox/draw.sh A
sleep $WAIT
/blackbox/draw.sh B
sleep $WAIT
/blackbox/draw.sh C
sleep $WAIT
/blackbox/draw.sh D
sleep $WAIT
/blackbox/draw.sh E
sleep $WAIT
/blackbox/draw.sh F
sleep $WAIT
/blackbox/draw.sh H
sleep $WAIT
/blackbox/draw.sh I
sleep $WAIT
/blackbox/draw.sh J
sleep $WAIT
/blackbox/draw.sh K
sleep $WAIT
/blackbox/draw.sh L
sleep $WAIT
/blackbox/draw.sh O
sleep $WAIT
/blackbox/draw.sh P
sleep $WAIT
/blackbox/draw.sh R
sleep $WAIT
/blackbox/draw.sh S
sleep $WAIT
/blackbox/draw.sh U
sleep $WAIT
/blackbox/draw.sh Z
sleep $WAIT
/blackbox/draw.sh CLEAR
